import Link from "next/link";
import Image from "next/image";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#09090b] text-white/80">
      <div className="mx-auto max-w-2xl px-5 py-16">
        <Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-white/45 hover:text-white transition-colors">
          <Image src="/images/logo-icon.png" alt="CarteAI" width={24} height={24} className="rounded" />
          <span className="font-medium text-white">CarteAI</span>
          <span>&larr; Back to home</span>
        </Link>
        <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/40">Last updated: May 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white">1. Service Description</h2>
            <p className="mt-3">
              CarteAI provides an AI-powered menu concierge for restaurants. Restaurant owners upload menus; diners scan QR codes to receive personalized dish recommendations based on budget, dietary preferences, and allergen restrictions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">2. Allergen Disclaimer</h2>
            <p className="mt-3">
              Allergen, ingredient, and calorie information displayed by CarteAI is based on data provided by the restaurant. CarteAI does not independently verify this information. <strong className="text-white">Diners with allergies must always confirm with restaurant staff before ordering.</strong> CarteAI is not liable for allergic reactions resulting from inaccurate menu data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">3. AI Recommendations</h2>
            <p className="mt-3">
              Recommendations are generated by AI and are suggestions only. They do not constitute dietary, medical, or nutritional advice. AI-generated reference images may not accurately represent actual dishes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">4. Restaurant Owner Responsibilities</h2>
            <ul className="mt-3 list-disc pl-5 space-y-1.5">
              <li>Keep menu data accurate and up to date.</li>
              <li>Ensure allergen information is correct to the best of your knowledge.</li>
              <li>You retain ownership of all menu content you upload.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">5. Acceptable Use</h2>
            <p className="mt-3">
              You agree not to misuse the service, including uploading false menu data, attempting to reverse-engineer the AI system, or using the service for any unlawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">6. Service Availability</h2>
            <p className="mt-3">
              CarteAI is provided &ldquo;as is&rdquo; without warranty. We strive for high availability but do not guarantee uninterrupted service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">7. Changes</h2>
            <p className="mt-3">
              We may update these terms. Continued use of the service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white">8. Contact</h2>
            <p className="mt-3">
              For questions about these terms, contact us at <a href="mailto:legal@carte-ai.link" className="text-emerald-400 hover:underline">legal@carte-ai.link</a>.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
