import Link from "next/link";
import Image from "next/image";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12">
      <Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
        <Image src="/images/logo-icon.png" alt="CarteAI" width={24} height={24} className="rounded" />
        <span className="font-medium">CarteAI</span>
        <span>&larr; Back to home</span>
      </Link>
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: May 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/80">
        <section>
          <h2 className="text-lg font-semibold text-foreground">1. Service Description</h2>
          <p className="mt-2">
            CarteAI provides an AI-powered menu concierge for restaurants. Restaurant owners upload menus; diners scan QR codes to receive personalized dish recommendations based on budget, dietary preferences, and allergen restrictions.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">2. Allergen Disclaimer</h2>
          <p className="mt-2">
            Allergen, ingredient, and calorie information displayed by CarteAI is based on data provided by the restaurant. CarteAI does not independently verify this information. <strong>Diners with allergies must always confirm with restaurant staff before ordering.</strong> CarteAI is not liable for allergic reactions resulting from inaccurate menu data.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">3. AI Recommendations</h2>
          <p className="mt-2">
            Recommendations are generated by AI and are suggestions only. They do not constitute dietary, medical, or nutritional advice. AI-generated reference images may not accurately represent actual dishes.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">4. Restaurant Owner Responsibilities</h2>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Keep menu data accurate and up to date.</li>
            <li>Ensure allergen information is correct to the best of your knowledge.</li>
            <li>You retain ownership of all menu content you upload.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">5. Acceptable Use</h2>
          <p className="mt-2">
            You agree not to misuse the service, including uploading false menu data, attempting to reverse-engineer the AI system, or using the service for any unlawful purpose.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">6. Service Availability</h2>
          <p className="mt-2">
            CarteAI is provided &ldquo;as is&rdquo; without warranty. We strive for high availability but do not guarantee uninterrupted service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">7. Changes</h2>
          <p className="mt-2">
            We may update these terms. Continued use of the service after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground">8. Contact</h2>
          <p className="mt-2">
            For questions about these terms, contact us at legal@carte-ai.link.
          </p>
        </section>
      </div>
    </main>
  );
}
